### ISSUE TITLE
[QAIT] Ezi-Pay> ‘Your details screen’: Enter email address in invalid format> Application displays validation ‘’Enter an email address’ along with error message ‘'Email is not a valid email'’

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-magento-2.x#3] opened 2017-11-09 05:53 UTC
**Test Data:** This issue is reproducible on following devices:
Safari with iOS 11.1
Chrome 62 with Android 7
Samsung Internet/Android 7
Android Webview/Android 7

**Pre-requisite:**
Admin has configured the ‘Ezi-pay’ for AU region

**Steps to reproduce:**
1. Launch the site: http://ec2-13-210-68-144.ap-southeast-2.compute.amazonaws.com
2. Add products in cart
3. Tap on ‘Proceed to Checkout’ button
4. Enter shipping address
5. Select payment method as ‘Ezi-Pay’ and tap on ‘Place Order’ button
7. Verify the phone number on ‘Verify Mobile screen
8. Confirm the mobile numbering by entering verification code and tap on ‘Submit’ button
9. Verify that user is directed to ‘Your details screen'
10. Enter email address in invalid format say ‘vishuaroraqainfotech.com’
11. Tap on ‘Submit’ button
12. Verify the result

**Actual Result:** Application displays validation ‘’Enter an email address" along with error message ‘'Email is not a valid email".

**Expected Result:** Application should only display an error message “Email is not a valid email'’ when user enters email address in invalid format.

**Comment by Vishuarora-qait** [comment] 2017-11-09 06:25
**Behaviour on iOS <<Email_Invalid.jpg>>** 

![email_invalid](https://user-images.githubusercontent.com/22979429/32591318-a3a31312-c544-11e7-8d7b-ee961d9f0216.jpg)

**Behaviour on Android <<Android_Email_Address**

![android_email_address](https://user-images.githubusercontent.com/22979429/32591384-d88769a2-c544-11e7-91c0-90b1f1dab3e4.jpg)
.jpg>>

**Comment by sam-flexi** [comment] 2017-11-13 04:15
Duplicate of [Issue #5](https://github.com/Certegy/certegy-ezipay-woocommerce/issues/6) reported on the WooCommerce Ezipay project.

**Closed as completed by sam-flexi** 2017-11-13 04:15 UTC
Labels: duplicate
