### ISSUE TITLE
[QAIT] Ezi-Pay> ‘Your details screen’: Focus does not get in to the month and year fields of ‘Date of Birth’ when user taps on it.

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-magento-2.x#4] opened 2017-11-09 06:36 UTC
**Test Data:** This issue is reproducible on following devices:
Safari with iOS 11.1
Chrome 62 with Android 7
Samsung Internet/Android 7
Android Webview/Android 7

**Pre-requisite:**
Admin has configured the ‘Ezi-pay’ for AU region

**Steps to reproduce:**
1. Launch the site: http://ec2-13-210-68-144.ap-southeast-2.compute.amazonaws.com
2. Add products in cart
3. Tap on ‘Proceed to Checkout’ button
4. Enter shipping address
5. Select payment method as ‘Ezi-Pay’ and tap on ‘Place Order’ button
7. Verify the phone number on ‘Verify Mobile screen
8. Confirm the mobile numbering by entering verification code and tap on ‘Submit’ button
9. Verify that user is directed to ‘Your details screen
10. Enter ‘Date of Birth’ and then tap on 'MM/YYYY' field to remove/edit the date of birth 
11. Verify the result

**Actual Result:** Focus does not get in to the month and year fields of ‘Date of Birth’ when user taps on it due to which user is not able to remove the values from ‘Date of Birth’ field.

Refer to the screen-cast<<http://screencast-o-matic.com/watch/cbXQ1a2lMk >> for more details

**Expected Result:** Focus should appear on month and year fields of 'Date of Birth' when user taps on it.

**Comment by Vishuarora-qait** [comment] 2017-11-09 06:38
**Observation:** Focus gets only into the 'Date' field of 'Date of Birth'.

**Comment by Vishuarora-qait** [comment] 2017-11-10 11:00
**Observation:** We have also observed below behavior on 'Date of Birth' field:

When user edits the date, application automatically moves focus to year field. Refer to the screencast <<http://screencast-o-matic.com/watch/cbX668222e  >> for more details

**Comment by sam-flexi** [comment] 2017-11-13 04:13
Duplicate of [Issue 7](https://github.com/Certegy/certegy-ezipay-woocommerce/issues/7) reported on the WooCommerce Ezipay project.

**Closed as completed** 2017-11-13 04:13 UTC
Labels: duplicate
